"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Button } from "@/components/ui/button"
import { useRouter } from "next/navigation"

import FooterSection from "@/components/section/footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  const router = useRouter();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex flex-rows justify-between items-center bg-[#262626] h-18 w-full">

          <button className="pl-8 text-white text-2xl px-3 py-2 cursor-pointer" onClick={() => router.push("/")}>Pasin's Portfolio</button>

          <div className="flex flex-rows items-center justify-center pr-10 gap-3 text-xl">
            <button className="text-white px-3 py-2 cursor-pointer" onClick={() => router.push("/")}>Home</button>
            <button className="text-white px-3 py-2 cursor-pointer" onClick={() => router.push("/works")}>Works</button>
            <button className="text-white px-3 py-2 cursor-pointer" onClick={() => router.push("/certificates")}>Certificates</button>
            <button className="text-white px-3 py-2 cursor-pointer" onClick={() => router.push("/aboutme")}>About me</button>
          </div>

        </header>

        <main className="flex-1">
          {children}
        </main>

        <FooterSection />
      </body>
    </html>
  );
}
